### PR TITLE
Add example of pnet in IPFS

### LINKED ISSUE #3: Custom libp2p for browser based js-ipfs node (private network - swarmkey)
How can js-libptp-pnet be used to connect to a private network using a swarm.key? Any examples?

### PR DESCRIPTION
**Pull request by jacobheun**
This adds a working example of how to enable private networks with `libp2p-pnet` for IPFS nodes. It also includes a task for users to see what happens when nodes with different swarm keys are connected to show their inability to connect.

resolves #3

### CODE REVIEW

**Review by alanshaw — COMMENTED** [review]
Minor but IMHO examples work is "docs: ..." rather than "chore: ..." and also means that it makes it into the CHANGELOG for everyone to see.

**Comment by jacobheun** [comment]
@alanshaw yes, you are totally right. Thanks for catching that, I've rebased the commit.

**Comment by alanshaw** [comment]
@jacobheun you are awesome

**Review by vasco-santos — APPROVED** [review]
Looks great! Docs and examples  🚀

**Pull request merged**
